spring.application.name=Florio
spring.datasource.url=jdbc:postgresql://localhost:5432/florio
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret= ${JWT_SECRET:myVerySecretKeyThatIsAtLeast32CharactersLong123456}
jwt.expiration=43200000

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}

app.otp.expiry-minutes=10
app.otp.max-attempts=5
app.otp.cooldown-seconds=60